"use client";

import Link from "next/link";
import { ArrowLeft, FileText, Sun, Moon } from "lucide-react";
import { useTheme } from "@/lib/theme";

export default function TermsPage() {
  const { theme, toggleTheme } = useTheme();

  return (
    <div className="min-h-screen relative">
      {/* Header */}
      <header className="sticky top-0 z-50 glass-card border-b border-[var(--glass-border)] backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/" className="p-2 rounded-lg hover:bg-[var(--glass-hover)] transition-colors">
              <ArrowLeft className="w-4 h-4 text-[var(--text-muted)]" />
            </Link>
            <div className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-purple-400" />
              <h1 className="text-lg font-semibold text-[var(--text-primary)]">Terms of Service</h1>
            </div>
          </div>
          <button onClick={toggleTheme} className="p-2 rounded-lg hover:bg-[var(--glass-hover)] transition-colors">
            {theme === "dark" ? <Sun className="w-4 h-4 text-[var(--text-muted)]" /> : <Moon className="w-4 h-4 text-[var(--text-muted)]" />}
          </button>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <div className="glass-card p-8 sm:p-12 space-y-8">
          <div>
            <p className="text-sm text-[var(--text-muted)] mb-2">Last updated: February 14, 2026</p>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              These Terms of Service (&quot;Terms&quot;) govern your use of TalentFlow AI (&quot;the Platform&quot;), operated by TalentFlow (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By using the Platform, you agree to these Terms.
            </p>
          </div>

          <Section title="1. Platform Description">
            <p className="text-[var(--text-secondary)] leading-relaxed">
              TalentFlow AI is an AI-powered recruiting pipeline that assists recruiters in evaluating candidate resumes, generating screening questions, and conducting outreach. The platform uses artificial intelligence throughout its workflow, and all AI-generated content is clearly disclosed.
            </p>
          </Section>

          <Section title="2. Use of AI">
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              By using this Platform, you acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
              <li>Resume evaluations, scores, and recommendations are generated by AI language models and should be treated as decision-support tools, not final hiring decisions</li>
              <li>Screening questions are AI-generated and should be reviewed by a human recruiter before use in actual interviews</li>
              <li>Outreach emails and voice messages are AI-generated content and are clearly labeled as such</li>
              <li>AI evaluations may contain errors, biases, or inaccuracies despite our best efforts to prevent them</li>
              <li>Final hiring decisions must always involve human judgment and should never rely solely on AI-generated scores</li>
            </ul>
          </Section>

          <Section title="3. Candidate Rights">
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              Candidates whose resumes are processed through the Platform have the following rights:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
              <li>The right to know their data is being processed by AI systems</li>
              <li>The right to request human review of any AI-generated evaluation</li>
              <li>The right to request deletion of their data from our systems</li>
              <li>The right to access any data held about them</li>
              <li>The right to contest AI-generated decisions that affect their candidacy</li>
            </ul>
          </Section>

          <Section title="4. Recruiter Responsibilities">
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              Recruiters using this Platform agree to:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
              <li>Review all AI-generated content before making hiring decisions</li>
              <li>Not use AI scores as the sole basis for rejecting candidates</li>
              <li>Comply with all applicable employment laws and anti-discrimination regulations</li>
              <li>Obtain candidate consent before processing their resume through the AI pipeline</li>
              <li>Inform candidates that AI is used in the evaluation process when required by law</li>
              <li>Report any suspected bias or discriminatory outputs to us immediately</li>
            </ul>
          </Section>

          <Section title="5. Data Handling">
            <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
              <li>Resume data is processed in real-time and parsed text may be stored in our CRM for recruiter review</li>
              <li>No resume files are permanently stored on our servers</li>
              <li>AI evaluation data is transient and held in server memory during the session</li>
              <li>For full data handling details, see our <Link href="/privacy" className="text-purple-400 hover:underline">Privacy Policy</Link></li>
            </ul>
          </Section>

          <Section title="6. Prohibited Uses">
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              You agree NOT to use the Platform to:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
              <li>Discriminate against candidates based on protected characteristics (race, gender, age, religion, disability, national origin, etc.)</li>
              <li>Make automated hiring decisions without human oversight</li>
              <li>Process resumes without candidate knowledge or consent</li>
              <li>Attempt to extract or reverse-engineer AI model weights or training data</li>
              <li>Submit false, misleading, or malicious data to the Platform</li>
              <li>Use the Platform for any purpose that violates applicable laws</li>
            </ul>
          </Section>

          <Section title="7. Disclaimer of Warranties">
            <p className="text-[var(--text-secondary)] leading-relaxed">
              The Platform is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that AI evaluations will be error-free, unbiased, or suitable for any particular hiring decision. AI models may produce inconsistent results across different runs. We continuously monitor and test for bias but cannot guarantee its complete absence.
            </p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p className="text-[var(--text-secondary)] leading-relaxed">
              To the maximum extent permitted by law, TalentFlow shall not be liable for any hiring decisions made based on AI-generated evaluations, any damages arising from AI bias or errors, or any consequential losses resulting from use of the Platform. Users are responsible for exercising their own judgment in all hiring decisions.
            </p>
          </Section>

          <Section title="9. AI Ethics Commitment">
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              We are committed to responsible AI use in recruiting:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
              <li>We run automated ethics evaluations covering fairness, safety, quality, transparency, inclusivity, and performance</li>
              <li>All AI touchpoints are documented and auditable</li>
              <li>We test for demographic bias across diverse candidate profiles</li>
              <li>Our AI systems are explicitly instructed to refuse discriminatory requests</li>
              <li>Ethics evaluation results are available on the <Link href="/eval" className="text-purple-400 hover:underline">AI Ethics Dashboard</Link></li>
            </ul>
          </Section>

          <Section title="10. Changes to Terms">
            <p className="text-[var(--text-secondary)] leading-relaxed">
              We reserve the right to modify these Terms at any time. Changes will be posted on this page. Continued use of the Platform after changes constitutes acceptance of the updated Terms.
            </p>
          </Section>

          <Section title="11. Contact">
            <p className="text-[var(--text-secondary)] leading-relaxed">
              For questions about these Terms, contact us at{" "}
              <a href="mailto:recruiting@talentflow.elunari.uk" className="text-purple-400 hover:underline">
                recruiting@talentflow.elunari.uk
              </a>.
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">{title}</h2>
      {children}
    </section>
  );
}
